### ISSUE TITLE
mkdir needs -p

### ISSUE THREAD

**Issue by thermionic** [ghostseven/LEUBNT#1]
Line 27 includes mkdir /config/lighttpd/conf-enabled

if the directory /config/lighthttpd does not exist, it is not possible to create /config/lighttpd/conf-enabled without -p

**Comment by ghostseven** [comment]
Ergh, yep that is not right I think. Will check, half wake today and cant read my own code.

**Comment by ghostseven** [comment]
Coffee imbibed, code read, yurp thats going to fail as it need to create parent directories.  Fixed ! Thank you @thermionic
